### ISSUE TITLE
[!] Nuitka magic header mismatch

### ISSUE THREAD

**Issue by Nagz06** [extremecoders-re/nuitka-extractor#4]
C:\User\ToolBin>nuitka-extractor.exe App.exe
[+] Processing App.exe
[+] File type: PE
[+] Payload size: -6899338464066494456 bytes
[!] Nuitka magic header mismatch

**Comment by ns-cpp** [comment]
Did you find a solution to the error?

**Comment by Nagz06** [comment]
Nope

**Comment by ns-cpp** [comment]
I found a solution but I don't understand what to do. you should try.
https://giters.com/extremecoders-re/nuitka-extractor/issues/2

**Comment by Nagz06** [comment]
Thanks, I'll check it out.

**Comment by ns-cpp** [comment]
waiting for your feedback after checking

**Comment by James404-cyber** [comment]
Your need to make it automated remove the mismatch issue and decompile, if it’s manually use hex editor there are many more issue.

**Comment by extremecoders-re** [comment]
Please upload the file somewhere if you want me to take a look.

**Comment by extremecoders-re** [comment]
Please try with the latest release. Should successfully extract both of your files.
