### ISSUE TITLE
how to run it please

### ISSUE THREAD

**Issue by codes-team** [extremecoders-re/nuitka-extractor#6]
# command-line-arguments
./main.go:67:20: undefined: LocateRCDataEnd

**Comment by extremecoders-re** [comment]
If you are trying from source

```
go run . file.exe
```

or do

```
go build
```

and then run the compiled exe

**Comment by codes-team** [comment]
> If you are trying from source
> 
> ```
> go run . file.exe
> ```
> 
> or do
> 
> ```
> go build
> ```
> 
> and then run the compiled exe
> 
> Also precompiled binaries are already available in Releases.
> https://github.com/extremecoders-re/nuitka-extractor/releases

thank you so much it's work
